### ISSUE TITLE
Annoyances with counsel/ivy's find-file path handling

### ISSUE THREAD

**Issue by bdowning** [abo-abo/swiper#1424]
The way ivy's and counsel's path handling behaves in their various find-file like modes has a few quirks that I'm having a hard time getting used to.  Some are just "probably need to get used to" things, but others I'd probably classify as bugs or at least surprising.

Buggish:

* Undo doesn't work correctly to undo directory changes.  In ordinary find-file I would use "M-backspace" to peel off directories from the end of the path.  If I went too far I could hit "C-/" to get them back.  In Ivy once the directories are gone there doesn't seem to be a way to undo back into them, and "C-/" does nothing.

Annoyance:

* Backspace behaves inconsistently; it kills a whole directory level if and only if you've "completed" into that directory, otherwise deleting only a character.  I find I prefer the basic find-file model where the whole path is just treated as a string, and editing commands work normally; i.e. backspace just removes a single character even if you're going "back" a path; this also makes undo (and other editing commands) work as expected as described above.  Is there any way to get this behavior back?  My muscle-memory is to hit "M-backspace" to peel off directories, which also works, but the backspace thing trips me up a lot.

* In ordinary find-file, if I want to get to my home directory no matter where I start, I type "\~/" and keep going.  In Ivy/Counsel, "\~" instantly sends me to my home directory, then the following "/" leaves me with "\~//" on the find file line, and this seems to result in its behavior being generally not useful until I get rid of the extra slash.  I'd expect either the second slash to be ignored (as is normal Unix behavior, i.e. "cat /etc////issue" is the same as "cat /etc/issue") or the second slash to take you back to the root directory (as seemed to be the normal find-file behavior when it encountered a double-slash; note however that my use-case above worked correctly as no second slash occurred).  This "magic" behavior on "\~" also makes it very difficult to get to another home directory; i.e. "\~bdowning" tries to find "\~/bdowning" rather than bdowning's home directory, again unlike find-file and the plain shell.

Any hints as to how to resolve these issues would be greatly appreciated.  Otherwise I like most of the Ivy workflow.

**Comment by abo-abo** [comment]
> Undo doesn't work correctly to undo directory changes. In ordinary find-file I would use "M-backspace" to peel off directories from the end of the path. If I went too far I could hit "C-/" to get them back. In Ivy once the directories are gone there doesn't seem to be a way to undo back into them, and "C-/" does nothing.

This could be added as feature. Although I haven't missed it much in the last few years of usage.

> Backspace behaves inconsistently; it kills a whole directory level if and only if you've "completed" into that directory, otherwise deleting only a character. I find I prefer the basic find-file model where the whole path is just treated as a string, and editing commands work normally; i.e. backspace just removes a single character even if you're going "back" a path; this also makes undo (and other editing commands) work as expected as described above. Is there any way to get this behavior back? My muscle-memory is to hit "M-backspace" to peel off directories, which also works, but the backspace thing trips me up a lot.

This works as designed, backspace is the recommended way to go up-directory.

> In ordinary find-file, if I want to get to my home directory no matter where I start, I type "~/" and keep going. In Ivy/Counsel, "~" instantly sends me to my home directory, then the following "/" leaves me with "~//" on the find file line, and this seems to result in its behavior being generally not useful until I get rid of the extra slash. I'd expect either the second slash to be ignored (as is normal Unix behavior, i.e. "cat /etc////issue" is the same as "cat /etc/issue") or the second slash to take you back to the root directory (as seemed to be the normal find-file behavior when it encountered a double-slash; note however that my use-case above worked correctly as no second slash occurred).

Customize `ivy-magic-tilde`.

> This "magic" behavior on "~" also makes it very difficult to get to another home directory; i.e. "~bdowning" tries to find "~/bdowning" rather than bdowning's home directory, again unlike find-file and the plain shell.

The recommended way is to press <kbd>~ DEL</kbd>.

**Comment by immerrr** [comment]
> Undo doesn't work correctly to undo directory changes.

Same happens to me more times than I'm proud of being one of the few annoyances that nudge me back to helm.

**Comment by kislyuk** [comment]
> This works as designed, backspace is the recommended way to go up-directory.

Please consider adding a configuration option for this. I think it's surprising and unintuitive when this happens.

**Comment by abo-abo** [comment]
I think this issue is now addressed by the <kbd>C-M-y</kbd> binding that allows you to edit the current path.

**Comment by immerrr** [comment]
@abo-abo thanks for the <kbd>C-M-y</kbd> tip, didn't know about it. I still experience some of the inconveniences. Here's an example if it helps.

Imagine a directory tree like this one:
```
$ tree
.
├── foo-bar-baz
│   └── test.txt
├── foo-bar-quxinator
│   └── test.txt
└── foo-bar-qux
    └── test.txt
```

I want to get to `foo-bar-quxinator/test.txt` file. I type `foo` and press <kbd>TAB</kbd> to auto-complete the common part:
![image](https://user-images.githubusercontent.com/579798/81040105-e2455300-8eaa-11ea-8295-5ebc3904d494.png)


I then mindlessly enter `qux` and press <kbd>TAB</kbd> to complete the long word, but end up in  `qux` directory instead:
![image](https://user-images.githubusercontent.com/579798/81040196-16b90f00-8eab-11ea-96af-d23d0203b192.png)
![image](https://user-images.githubusercontent.com/579798/81040207-20427700-8eab-11ea-8586-f66f9dca81b2.png)

I realise my mistake, and want to correct it. If I press backspace, the entire directory level is removed and I need to re-type it back:
![image](https://user-images.githubusercontent.com/579798/81040226-2fc1c000-8eab-11ea-831e-dd2b32c9a0fa.png)

If I use <kbd>C-M-y</kbd>, the path is indeed inserted and I can remove just the slash, or maybe a couple of mistyped characters, but I lose completion:
![image](https://user-images.githubusercontent.com/579798/81040300-5ed83180-8eab-11ea-90c3-94e794bf87f5.png)

Is there a way around this?

**Comment by kislyuk** [comment]
+1 - I stopped using swiper/counsel/ivy because of the issue @immerrr described. Would love a workaround.

**Comment by immerrr** [comment]
BTW, I have now realised that I never actually tried fixing this for myself, and we are in Emacs where everything is possible, so here goes my first attempt.

It binds two functions to `DEL` and `M-DEL` that forward the primary functionality to  `ivy-backward-delete-char` and `ivy-backward-kill-word` respectively, but first, if there is no minibuffer content to remove, would go up one directory and then reinsert that directory name as an editable string.

```elisp
(defun mmr-ivy-make-current-directory-editable ()
  "Make last component of directory path editable in ivy minibuffer."
  (interactive)
  (let* ((current-prompt (minibuffer-contents-no-properties))
         (current-offset-from-max (- (point-max) (point)))
         (dir-path (and ivy--directory
                        (directory-file-name (expand-file-name ivy--directory))))
         (dir-name (and dir-path (file-name-nondirectory dir-path))))
    (when dir-name
      (ivy--cd (ivy--parent-dir (expand-file-name ivy--directory)))
      (insert (format "%s/%s" dir-name current-prompt))
      (goto-char (- (point-max) current-offset-from-max)))))

(defun mmr-ivy-backward-delete-char ()
  "Forward to `ivy-backward-delete-char'.

But first, if there's no more content in minibuffer to delete,
try making last component of directory path editable."
  (interactive)
  (when (and ivy--directory (= (minibuffer-prompt-end) (point)))
    (mmr-ivy-make-current-directory-editable))
  (call-interactively #'ivy-backward-delete-char))

(defun mmr-ivy-backward-kill-word ()
  "Forward to `ivy-backward-kill-word'.

But first, if there's no more content in minibuffer to delete,
try making last component of directory path editable."
  (interactive)
  (when (and ivy--directory (= (minibuffer-prompt-end) (point)))
    (mmr-ivy-make-current-directory-editable))
  (call-interactively #'ivy-backward-kill-word))

(let ((map ivy-minibuffer-map))
  (define-key map [remap delete-backward-char] 'mmr-ivy-backward-delete-char)
  (define-key map [remap backward-delete-char-untabify] 'mmr-ivy-backward-delete-char)
  (define-key map [remap backward-kill-word] 'mmr-ivy-backward-kill-word))

```

**Comment by abo-abo** [comment]
> I then mindlessly enter `qux` and press TAB to complete the long word, but end up in `qux` directory instead:

I assume you do a double TAB here, since a single TAB will not change the current directory.

Here's a solution that's already possible: <kbd>C-DEL M-i</kbd>:

- <kbd>C-DEL</kbd> will go up a level and pre-select the last directory
- <kbd>M-i</kbd> will insert the current candidate, i.e. the last directory

In this particular case, <kbd>C-DEL C-n</kbd> will do the same.

**Comment by immerrr** [comment]
Yep, that was indeed double <kbd>TAB</kbd>.

I am not sure I see <kbd>C-DEL M-i</kbd> as a viable alternative. It does not pre-select the last directory for me for some reason, but that's not the point. Even if it did, let me try to explain my perspective.

First, I need to unlearn the muscle memory that tells me to use backspace to delete characters backwards. Pressing backspace to delete a character behind cursor is like an instinct after ~25 years behind keyboard. So unlearning this will be a long process, and I will be making a lot of mistakes. Those mistakes would be especially maddening because undo-tree does not work very well (for me?) when ivy is switching directories either. 

And even after I master the `C-DEL M-i` combo, it is still 4 different keys to press to make one slash go away. And I need to remember that all that happens with only one package, in only one mode of functioning, and everywhere else it is business as usual w.r.t. the backspace key.

So for me, it is not a question of whether or not it is possible, it's a matter of ergonomics. Just like with the old proverb saying that Emacs is a great operating system that just lacks a decent text editor.

Anyway, I can respect the decision to do what you feel is right with your own package. And don't get me wrong, I am grateful for it, it is a great piece of software, thank you! We are in Emacs world and everything can be bent a little bit here and there, so I can make do. Besides, the tweak I pasted above does not even feel that hackish. I am actually somewhat embarrassed to admit that I struggled for more than 2 years with this — going to helm and back just because of this idiosyncrasy — when the workaround that has taken all the pain away took me less than an hour to implement.

**Comment by kislyuk** [comment]
I'm just going to +1 the statement from @immerrr about muscle memory. It is extremely important and I think any tool that interferes with the muscle memory of (in this case) emacs is setting itself up for a lot of unnecessary pain. Personally, I could not make my muscle memory work with swiper the way the key bindings work right now.

**Comment by abo-abo** [comment]
I've made several improvements to make your use case better:

- You can now press <kbd>DEL M-i</kbd>
- You can now use your `undo` binding (<kbd>C-/</kbd> in default Emacs)

The latter is more convenient, I think.

**Comment by immerrr** [comment]
Thanks, I appreciate it! Having undo fixed is a tremendous improvement!

And I'm glad we are on the same page on that having to press less keys is more convenient :)

**Comment by haoyuan80s** [comment]
An extra `C-/` will pop the `ivy--directory-hist`, and make this function "broken":
Good path:
`foo/bar/`
`backspace`  ->`foo/`
`C-/`  -> `foo/bar/`

Bad path:
`foo/bar/`
`C-/`  -> `foo/bar/`            (path unchanged, but the `ivy--directory-hist` is popped)
`backspace`  ->`foo/`
`C-/`  -> `foo/`                   (Cannot undo here! expect 'foo/bar/')

The example looks artificial, but happens often to me: When I want to undo something to the beginning, I keep tapping many `C-/`s.

I added an `if (> (length ivy--directory-hist) 1)` to fix it:

```
(defun counsel-find-file-undo ()
  (interactive)
  (if (> (length ivy--directory-hist) 1)
      (if (string= ivy-text "")
	  (let ((dir (progn
                       (pop ivy--directory-hist)
                       (pop ivy--directory-hist))))
            (when dir
              (ivy--cd dir)))
	(undo))))
```

**Comment by AlynxZhou** [comment]
Setting `ivy-magic-tilde` to `nil` also helps me a lot! But I still have a question, if I continue to press backspace, fs root's `/` cannot be deleted. This causes some wired behavior, for example press `~`, it will show `/~`. And if I press `C-M-y` to edit this line, it will give me `Find file: //` (see my screenshot). So I think if there are options to make leading `/` removable, it will looks better.

![Screenshot from 2022-02-17 20-11-17](https://user-images.githubusercontent.com/8444615/154479366-8f4045fd-2064-4150-8219-f0369e93cf98.png)
